### ISSUE TITLE
Community health files checklist

### ISSUE THREAD

**Issue by tb148** [ScratchAddons/ScratchAddons#20]
These files are community healthfiles in the community profile [here](https://github.com/ScratchAddons/ScratchAddons/community)
- [x] Description (Technically not a file)
- [x] README
- [x] Code of conduct (#35)
- [x] Contributing guideline
- [x] License
- [x] Issue templates
- [x] PR templates
- [x] Repository admins accept content reports

**Comment by BoomerScratch** [comment]
I think we should discuss what our contributor guidelines will be.

**Comment by BoomerScratch** [comment]
Okay, contributing guidelines got added. Can this be closed?

**Comment by BoomerScratch** [comment]
In the community profile, there is also 'Repository admins accept content reports'.
I think @WorldLanguages should do it because [you need to open the settings](https://docs.github.com/en/github/building-a-strong-community/managing-reported-content-in-your-organizations-repository), and only the admin can.

**Comment by tb148** [comment]
> 
> 
> In the community profile, there is also 'Repository admins accept content reports'.
> I think @WorldLanguages should do it because [you need to open the settings](https://docs.github.com/en/github/building-a-strong-community/managing-reported-content-in-your-organizations-repository), and only the admin can.

Added as the 8th task!

**Comment by WorldLanguages** [comment]
Hmm, I'm not familiar with this GitHub feature. Is this what I was supposed to enable? 
![image](https://user-images.githubusercontent.com/17484114/89809854-8544e300-db12-11ea-9254-73c40faedc2b.png)

**Comment by tb148** [comment]
> 
> 
> Hmm, I'm not familiar with this GitHub feature. Is this what I was supposed to enable?
> ![image](https://user-images.githubusercontent.com/17484114/89809854-8544e300-db12-11ea-9254-73c40faedc2b.png)

Yes! Closed because all tasks are done!
