### ISSUE TITLE
Prepare for new studio page

### ISSUE THREAD

**Issue by apple502j** [ScratchAddons/ScratchAddons#2484]
- [x] exact-count: see #2491 - we might want to remove support - pr: #2492
- [x] infinite-scroll #2493
- [x] studio-tools #2493
- [x] CS anti-comment code (edit: #2486)
- [X] dark-www #2485 
- [X] scratchr2 (removing matches) #2485 
- [x] comments-linebreaks #2493
- [x] better-emojis #2493
- [x] confirm-actions #2493
- [x] copy-message-link #2493
- [x] more-links (We can no longer Iinkify descriptions, they are now disabled text areas instead of a div. That might change tho, because of @mentions and on scratch domain links) #2493
- [x] resizable-comment-input #2496
- [ ] scratch-messaging (#2046, they may be removing the old api)

**Comment by RedGuy12** [comment]
- [ ] dark-www
- [ ] scratchr2

**Comment by mxmou** [comment]
@RedGuy12 For these two adding something similar to #2416 to differentiate between old and new studios would be useful.

**Comment by WorldLanguages** [comment]
> @RedGuy12 For these two adding something similar to #2416 to differentiate between old and new studios would be useful.

@mxmou Creating a PR for that in a few minutes

**Comment by RedGuy12** [comment]
Tested better-emojies, it still works.

**Comment by RedGuy12** [comment]
- [ ] comments-linebreaks
- [ ] confirm-actions
- [ ] copy-message-link
- [ ] discuss-button (on my local copy of www it's going into the account dropdown instead of the navbar. Maybe they changed something?)
- [ ] infinite-scroll
- [ ] more-links (We can no longer Iinkify descriptions, they are now disabled text areas instead of a div. That might change tho, because of @mentions and on scratch domain links)
- [ ] resizable-comment-input
- [ ] scratch-messaging (#2046, they may be removing the old api)
- [ ] scratch-notifier (see above)
- [ ] studio-tools

**Comment by WorldLanguages** [comment]
@RedGuy12 scratch notifier only uses the comment fragment from the messages API, so it's not affected

**Comment by mxmou** [comment]
> discuss-button (on my local copy of www it's going into the account dropdown instead of the navbar. Maybe they changed something?)

I think that's because it checks for the `production` class, which is probably only present in a production environment. This is not a problem on the actual website, but replacing it with `dropdown` would solve this.
