### ISSUE TITLE
Roadmap next few versions (medium or big sized changes)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3170]
Edit 5 sep: this is outdated lol

**1.19** (~Aug 20)

**1.20** (~Sep 10)
- [ ] "Minor" and "forums" addon groups in settings page #2617 and https://github.com/ScratchAddons/ScratchAddons/pull/3155#issuecomment-890038913
- [ ] Drop `webRequestBlocking` permission. Depends on #2703, as well as making scratch-notifier's "mark as read" open a new tab.
- [ ] #2334 and #2110
- [ ] A way to remind the user a part of the UI is added by Scratch Addons (https://github.com/ScratchAddons/ScratchAddons/pull/2908#issuecomment-888595928)
- [ ] New minimum browser requirements https://github.com/ScratchAddons/ScratchAddons/issues/2599
- [ ] Cleaner settings page JavaScript and Vue logic, it's kinda messy right now
- [ ] Enable more addons by default, "featured" tag?

**1.21** (~Oct 1)
- Add some type of grid view to settings page so that we can include screenshots
- Refactor background page and persistent scripts to get ready to Manifest V3's service worker model. Make it possible for extension language to be changed, or at least keep it in mind (#2670). Also keep in mind two instances of Scratch Addons running at once, making it possible to run Scratch Addons in incognito mode.
- Add dynamicEnable to all addons where possible (and add settings page UX reminding the user to reload in cases where it's needed)

**1.22** (~Oct 22)
- Explore theming and superpresets: #2232, #1934
- Remove `persistent: true` from the background page. If this affects how late userstyles load (e.g. website dark mode) we might need to find some workaround with localStorage or similar.

**1.23** (~Nov 12)
- Minimum Chrome version 87 and use service workers in the background (while still in MV2) in Chrome. Service workers don't support modules, so if until 1.22 release that's still the case, we might need to use boring `importScripts()`

**Comment by WorldLanguages** [comment]
Honestly, wanting to migrate to service worker model is kick in the foot :P
But maybe we can at least support incognito and be better prepared for a potential forced update by the Chrome Web Store

**Comment by WorldLanguages** [comment]
lol for future reference, I wrote this before starting school :P
