### ISSUE TITLE
get-addon-settings.js migrations for v1.23.0

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#3861]
There will be more than one migration this release, ~~so it's better to code them all at once~~.

- [x]  #3878 Users that had the `editorCount` setting of `project-info` set to true, need to have the new `block-count` addon enabled (#3795)
- [ ] TBD what should be done about users on the old TurboWarp Dark preset after the update (#3839)
- [x] #3882 / Migrate scratchr2 settings to dark-www (https://github.com/ScratchAddons/ScratchAddons/pull/3710#issuecomment-952652969)
- [ ] TBD what should be done about users with the old Experimental Dark preset after the update (#3710)

Discussion for how presets should migrate is happening on https://github.com/ScratchAddons/ScratchAddons/discussions/3855

We could also remove old migration code by now.
And related, I find it funny that some users tell me they see dango in my profile still. Maybe the addon should be removed or made non-functional by now.
