### ISSUE TITLE
Block colors update support checklist

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#5309]
This issue is a to-do list for updating the Customizable block colors addon to take Scratch's upcoming block color switcher into account when it releases.

Discussion: #5192

- [x] Tweak the `editor-theme3` addon to make blocks look closer to the new colors (#5257)
  - Adjust the borders, text, etc.
- [x] Add a preset to use the new colors now (#5308)
- [x] Update the Debugger addon blocks' default colors to be consistent (#6152)
- [x] Add a preset for high contrast to `editor-theme3`'s [default setting values](https://github.com/ScratchAddons/ScratchAddons/blob/48106c8599fca407ded70aeb073085cd7b6b655a/addons/editor-theme3/addon.json#L196)

**Comment by WorldLanguages** [comment]
Should we change the colors of debugger's blocks depending on whether the user is on default colors or accessible colors?

**Comment by DNin01** [comment]
> Should we change the colors of debugger's blocks depending on whether the user is on default colors or accessible colors?

I think we definitely should.

**Comment by WorldLanguages** [comment]
> Should we change the colors of debugger's blocks depending on whether the user is on default colors or accessible colors?

I think this is the only pending TODO in this checklist.

**Comment by WorldLanguages** [comment]
> I think this is the only pending TODO in this checklist.

@DNin01 Can you confirm? If that's the only pending TODO I suggest creating a new issue for it with a priority-4 label.

**Comment by DNin01** [comment]
> > I think this is the only pending TODO in this checklist.
> 
> 
> 
> @DNin01 Can you confirm? If that's the only pending TODO I suggest creating a new issue for it with a priority-4 label.

Created issue: #6123

**Comment by WorldLanguages** [comment]
@DNin01 Can this be closed?

**Comment by DNin01** [comment]
> @DNin01 Can this be closed?

Yeah, we're pretty much done here.
