### ISSUE TITLE
Compatibility with upcoming Scratch updates (start of June)

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6030]
I intend to maintain this list of TODOs (some of which might deserve their own issue) related to the upcoming Scratch updates to the website and editor.
This includes avoiding compatibility issues and related ideas such as migrating user setting appropriately.

- [x] Customizable block colors (editor-theme3) is somewhat replaced by a dropdown in the menu bar of the editor. We need to consider how to prevent the UX from getting confusing. Included in #5905
- [ ] The editor's accent color will change. At minimum, we should perform a settings migration for users on the "Scratch's default users" preset of the editor-dark-mode addon (details to be discussed) #6074
- [ ] Same as above, but with dark-www's navigation bar color https://github.com/ScratchAddons/ScratchAddons/issues/6115
- [x] Specific checklist regarding block colors: #5309
- [x] Some addons don't work properly: #6103

**Comment by DNin01** [comment]
Should this be in the "Scratch color changes" milestone?

**Comment by fractioneater** [comment]
How exactly will `editor-theme3` get replaced? I'm assuming a lot of the addon's color options will be kept, but which ones will Scratch put in the editor?

Even better, can someone send the link to a PR of the new Scratch changes? I haven't been able to find it.

**Comment by mxmou** [comment]
> How exactly will `editor-theme3` get replaced? I'm assuming a lot of the addon's color options will be kept, but which ones will Scratch put in the editor?

There will be an option to switch between default and high contrast blocks.

> Even better, can someone send the link to a PR of the new Scratch changes so I can see for myself? I haven't been able to find it.

In scratch-gui, they're in the `beta` branch. The scratch-www PR is here: https://github.com/LLK/scratch-www/pull/7588

**Comment by Samq64** [comment]
> Maybe for editor-theme3, it could add a new "Custom" option to the dropdown that applies the custom block colors (probably also selecting it by default).

The problem with that is they'll eventually add themes that effect the whole editor, not just blocks. I can't think of any better solutions though.

**Comment by mxmou** [comment]
> Maybe for editor-theme3, it could add a new "Custom" option to the dropdown that applies the custom block colors (probably also selecting it by default).

We could also simply disable the theme picker when theme3 is enabled. There could be a tooltip with a link to the addon settings.

**Comment by DNin01** [comment]
> > Maybe for editor-theme3, it could add a new "Custom" option to the dropdown that applies the custom block colors (probably also selecting it by default).
> 
> 
> 
> We could also simply disable the theme picker when theme3 is enabled. There could be a tooltip with a link to the addon settings.

But what about the upcoming dark theme? If we did this, users wouldn't be able to switch between themes.

We can do this now since the dark theme hasn't been rolled out yet, but once it's released, we should keep the color picker visible unless both `editor-theme3` and `editor-dark-mode` are enabled, potentially adding a message inside the theme picker drop-down menu to tell the user that some colors were overridden.

**Comment by Secret-chest** [comment]
There should be addons to disable the language label and the theme picker.

**Comment by DNin01** [comment]
> There should be addons to disable the language label and the theme picker.

We could probably remove the text but I don't know about hiding them completely.

**Comment by fractioneater** [comment]
> There should be addons to disable the language label and the theme picker.

I strongly agree with the first part. The language label takes up an impractical amount of space even without all addons disabled, but with `mediarecorder`, `block-count` and all of the other addons that take up navigation bar space enabled, it comes close to overflowing on small screens.

**Comment by DNin01** [comment]
> There should be addons to disable the language label and the theme picker.

I'm not sure if hiding the text labels needs to be an option that the user can choose as long as they don't actively get in the way, and I don't think they would without any addons that add to the menu bar, but we could automatically hide them if the menu bar gets too full. Remember, Scratch does this automatically on small screens:
> Icon only when <= 1024 px:
> 
> ![Screenshot 2023-03-13 at 2 25 26 PM](https://user-images.githubusercontent.com/4893763/224796702-42b3af44-68f7-4ff6-8b63-3de0f46aef87.png)

**Comment by DNin01** [comment]
Look! You can access it from https://scratchfoundation.github.io/scratch-gui/beta/.

**Comment by Secret-chest** [comment]
The theme picker is USELESS if you have a custom theme, and I don't want always seeing ROMÂNĂ at the top of my screen, even if there is free space, since it clutters the screen.

**Comment by BroJac5246** [comment]
> The theme picker is USELESS if you have a custom theme, and I don't want always seeing ROMÂNĂ at the top of my screen, even if there is free space, since it clutters the screen.

My thoughts exactly. If a user has the customizable block colors addon enabled, then they don't need the custom theme button.

**Comment by WorldLanguages** [comment]
Related: #6053

**Comment by DNin01** [comment]
> The theme picker is USELESS if you have a custom theme, and I don't want always seeing ROMÂNĂ at the top of my screen, even if there is free space, since it clutters the screen.

Update: They are packing the language and theme buttons into a dropdown menu, which I think is better. Probably don't need an addon to hide these anymore.

![Screenshot 2023-05-17 at 1 00 02 PM](https://user-images.githubusercontent.com/4893763/239027130-43ffd589-b442-4b21-8e2d-321b53f42a36.png)

**Comment by WorldLanguages** [comment]
> But what about the upcoming dark theme? If we did this, users wouldn't be able to switch between themes.

Is a dark theme really planned?

**Comment by DNin01** [comment]
> > But what about the upcoming dark theme? If we did this, users wouldn't be able to switch between themes.
> 
> Is a dark theme really planned?

I don't think it will be released in the upcoming update, so we don't need to worry about that for now. In the future, we can come back to that.

**Comment by WorldLanguages** [comment]
Closing this. The milestone is working as a checklist.
