### ISSUE TITLE
Coding experience checklist

### ISSUE THREAD

**Issue by DNin01** [ScratchAddons/ScratchAddons#6721]
As a welcoming open-source project, it's important to make sure contributors have a good experience. Enhancing the process of writing code with guidance along the way is one step closer.

- [ ] Code style preferences out of the box: #6621
- [ ] Explain how to open a folder in Visual Studio Code so the settings apply
- [ ] Code snippets for quick code autocomplete: #6641
- [ ] Recommend helpful extensions: #6593
- [ ] JSDoc types to explain `addon.*` APIs: #6488
- [ ] Make directories belonging to addons easier to search instead of having to scramble to find the addon ID you're looking for
