### ISSUE TITLE
Manifest V3: Master branch is now Manifest V3

### ISSUE THREAD

**Issue by WorldLanguages** [ScratchAddons/ScratchAddons#6876]
# See pull request: #7387

### The news

Google [recently announced](https://developer.chrome.com/blog/resuming-the-transition-to-mv3/) that they will begin disabling Manifest V2 extensions in pre-stable versions of Chrome (Dev, Canary, and Beta) as early as June 2024, in Chrome 127 and later. Users impacted by the rollout will see Manifest V2 extensions automatically disabled in their browser and will no longer be able to install Manifest V2 extensions from the Chrome Web Store. "We expect it will take at least a month to observe and stabilize the changes in pre-stable before expanding the rollout to stable channel Chrome, where it will also gradually roll out over time."
They have announced this already one year ago, but most likely this will actually happen this time.

### What does this mean for Scratch Addons?

**We will upload a Manifest V3 version of the extension to the Chrome Web Store before June 2024.**
As an indirect consequence, our minimum browser requirements will be affected as well. We currently support, to some extent, browsers versions as old as Chrome 80, released in 2020. We will increase the minum requirement to, at least, Chrome 92 (mid-2021). Older browsers won't be able to run the extension, as they don't know what a manifest three extension is, so it's not possible to show a "unsupported browser" screen in those cases.

### Plans on end-user browser support

This is the plan I had in mind to keep up with Chrome's requirements.

1. **Add the "export settings" and "view settings as file" buttons to the Unsupported Browser page.**
This will allow users running old browser versions to export their settings before the extension goes away.

2. **We will release a typical MV2 update which will increase the minimum browser requirements to match the MV3 requirements.**
We will not change our minimum browser requirements as we upgrade to MV3. We will do it earlier. As I said, we can't show any screens or buttons to Chrome versions that don't support basic MV3 functionality, so we have to block them from using the extension earlier.

### Plans on local development and browser support

Our current MV2 extension has a `manifest.json` file at root which is accepted by both Chrome and Firefox. They both log warnings, but the raw extension folder as uploaded to GitHub is accepted by both.
We plan to change the `manifest_version` of our manifest file to `3`, so all local development will use an MV3 extension, both in Chrome and Firefox.

This means contributors will need modern Firefox versions that support MV3, as well as [modern Chromium versions that don't reject Firefox-friendly manifest files](https://github.com/w3c/webextensions/issues/282#issuecomment-1786857524). Apparently, it's going to be Chrome 121+ and Firefox 121+ (coincidentally, it's the same version number!)

The [Installing - scratchaddons.com](https://scratchaddons.com/docs/getting-started/installing/) page will need tweaking to clarify this discrepancy between min browser for releases and min browser for development. It would also be nice if that page was more intuitive, as the install buttons don't look like buttons, and it's one of the most visited pages on our website.

As a side-effect, this could mean we could take advantage of CSS nesting and other features, and transpile the CSS when sending the releases to the stores, for wider browser support. This is just a comment, though.

### Background pages, service workers, and addons

Some of the "core" extension code will need some changes. But userscripts, userstyles, the settings page, and most parts of the extension every-day contributors check, won't be affected.

**Comment by WorldLanguages** [comment]
Please send a post if you have any questions. I could have forgotten some answers in the first post of this issue.

**Comment by DNin01** [comment]
Agreed with releasing an MV2 version of the extension for the purpose of disabling it in browsers that won't support the MV3 version.

I think a good time to show any unsupported browser notifications would be as the user opens the Scratch website. We should only open the page once per session or every time the user tries to open the Scratch Addons popup or settings page. We should also tell them how to disable or remove the extension so this page doesn't keep opening, and clarify that we're _no longer_ supported by their browser.

**Comment by WorldLanguages** [comment]
Don't forget we already have an Unsupported Browser page

**Comment by WorldLanguages** [comment]
Some Chrome version facts to consider:

- Chrome 87 and below don't know what manifest version 3 is, so they can't even load the extension.
- Chrome 92 and older require the background service worker to be at root (for example, `/background/sw.js` is not root). The extension continues to work normally, but with no background context available.
- Only Chrome 92 and above can load background service workers with `import` syntax of them.
- MV3 extensions cannot use `webRequestBlocking`, and its replacement `declarativeNetRequest` always asks for user permission, which is not nice. A permission called `declarativeNetRequestWithHostAccess` doesn't ask the user for permission, but it's only available since Chrome ~95.

So most likely this is what we'll attempt to support in our store releases:
- Older than Chrome 88: extension cannot be installed in any way.
- Older than Chrome 93: can be installed, will display Unsupported Browser page when clicked. No background runtime context available.
- Chrome 93, 94, 95?: some Scratch Messaging features might be broken, or we might add `declarativeNetRequest` to the optional permissions and ask these users to grant it.
- Chrome 95+ (Chrome versions from ~October 2021 and newer) ideally should have full support for core extension features and most addons.

**Comment by BroJac5246** [comment]
> So most likely this is what we'll attempt to support in our store releases:
> - Older than Chrome 88: extension cannot be installed in any way.

👍
> - Older than Chrome 93: can be installed, will display Unsupported Browser page when clicked. No background runtime context available.

👍
> - Chrome 93, 94, 95?: some Scratch Messaging features might be broken, or we might add `declarativeNetRequest` to the optional permissions and ask these users to grant it.

Those people really need to update their browser for security. Even if they're running Windows 8/8.1 or 7, they can update to I think 109. So we're not really cutting anyone out and we shouldn't give anyone a subpar experience. Plus then that's more work on our end to support probably like 5 users.
> - Chrome 95+ (Chrome versions from ~October 2021 and newer) ideally should have full support for core extension features and most addons.

👍

**Comment by DNin01** [comment]
> > * Chrome 93, 94, 95?: some Scratch Messaging features might be broken, or we might add `declarativeNetRequest` to the optional permissions and ask these users to grant it.
> 
> Those people really need to update their browser for security. Even if they're running Windows 8/8.1 or 7, they can update to I think 109. So we're not really cutting anyone out and we shouldn't give anyone a subpar experience. Plus then that's more work on our end to support probably like 5 users.

Yeah, that's not many versions to drop support for.

**Comment by Samq64** [comment]
> Those people really need to update their browser for security. Even if they're running Windows 8/8.1 or 7, they can update to I think 109. So we're not really cutting anyone out and we shouldn't give anyone a subpar experience. Plus then that's more work on our end to support probably like 5 users.

I think it's mostly older chromebooks that will be left out because they don't get very good support although I think it's gotten better.

**Comment by BroJac5246** [comment]
> > Those people really need to update their browser for security. Even if they're running Windows 8/8.1 or 7, they can update to I think 109. So we're not really cutting anyone out and we shouldn't give anyone a subpar experience. Plus then that's more work on our end to support probably like 5 users.
> 
> I think it's mostly older chromebooks that will be left out because they don't get very good support although I think it's gotten better.

Google just upped the support to 10 years, so hopefully this won't be a problem in the future. But here, it's a good bit of work for just a few users on three months' worth of the platform, so it's probably not worth it.

**Comment by GrahamSH-LLK** [comment]
We should probably add a message on extensions that are currently supported but won't be, right? Like a headsup

**Comment by WorldLanguages** [comment]
> We should probably add a message on extensions that are currently supported but won't be, right? Like a headsup

Users will still be able to export their settings for a reasonable period, so there's no real reason to notify them before that.

**Comment by DNin01** [comment]
Should we start an `mv3` branch for breaking changes? MV3 pull requests could merge into that branch, which could then be merged into `master` once we're ready.

<details><summary>For admins (click to expand)</summary>
<p>

Don't forget about the rules (you know, requiring 2 approvals per pull request). Here's a [screenshot](https://github.com/ScratchAddons/ScratchAddons/assets/106490990/acec981d-1b87-432e-829a-4fb271ca5537) of how they might be configured now. Maybe split it up into multiple rulesets named appropriately if you wish.

Things have evolved since we added branch protection rules to the `master` branch - an admin can create what's called a _ruleset_ [here](https://github.com/ScratchAddons/ScratchAddons/settings/rules). AFAIK, branch rules work in tandem with branch protections, but this would be a good time to make the switch to rules.

</p>
</details>

**Comment by WorldLanguages** [comment]
Yeah, I think we'll create an mv3 branch at some point.

**Comment by DNin01** [comment]
> Yeah, I think we'll create an mv3 branch at some point.

Yeah, right. Not right now.

**Comment by Hans5958** [comment]
> Should we start an `mv3` branch for breaking changes? MV3 pull requests could merge into that branch, which could then be merged into `master` once we're ready.

Reminder that we already have https://github.com/ScratchAddonsMV3/ScratchAddons, just because at that time we can't make forks on the same organization.

**Comment by Waakul** [comment]
i recommend we release this update as 2.0

**Comment by BroJac5246** [comment]
> i recommend we release this update as 2.0

That would be great but we don't have any 2.0 features to introduce.

**Comment by Waakul** [comment]
> Contributor

we do, me and hexagonal are working on a redesign

**Comment by BroJac5246** [comment]
> > Contributor
> 
> we do, me and hexagonal are working on a redesign

Sure but that's not a feature

**Comment by Hans5958** [comment]
> i recommend we release this update as 2.0

Wrong issue. Mention it on https://github.com/ScratchAddons/ScratchAddons/discussions/5103#discussioncomment-3631004.

**Comment by Waakul** [comment]
> > we do, me and hexagonal are working on a redesign
> 
> I am not an active part of the redesign. I participated in Waakul's redesign on Discord for fun, not knowing he was going to actually make it a reality. Waakul's redesign should be considered his project alone.

huh? see https://github.com/ScratchAddons/ScratchAddons/discussions/5103

**Comment by Waakul** [comment]
> > We should probably add a message on extensions that are currently supported but won't be, right? Like a headsup
> 
> Users will still be able to export their settings for a reasonable period, so there's no real reason to notify them before that.

maybe add a warning on the extension popup if their browser doesn't support mv3

**Comment by DNin01** [comment]
Well, if we're going to migrate to Manifest V3, we'd better keep pace and pick up now, because things usually take longer than expected. Four months will fly by fast and we need to be aware of how long this could take, considering that one of the things we need to address is the persistent background processes and variables, which shouldn't be active constantly, as per Google's guidelines.

**Comment by WorldLanguages** [comment]
Should we increase the minimum Chromium version to 95 then?
Chrome 95 was released back in [October 2021](https://chromereleases.googleblog.com/2021/10/stable-channel-update-for-desktop_19.html).

**Comment by Waakul** [comment]
i tried to merge the upstream into the develop-1 branch only to get 1714 merge conflicts

**Comment by WorldLanguages** [comment]
Hmm, we now need to figure out what the minimum Firefox version will be.

> Manifest V3 became generally available in Firefox 109
([source](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/))

**Comment by WorldLanguages** [comment]
> 2\. **We will release a typical MV2 update which will increase the minimum browser requirements to match the MV3 requirements.**
>     We will not change our minimum browser requirements as we upgrade to MV3. We will do it earlier. As I said, we can't show any screens or buttons to Chrome versions that don't support basic MV3 functionality, so we have to block them from using the extension earlier.

To clarify, I'm aiming for this for the upcoming March release.

**Comment by DNin01** [comment]
> i tried to merge the upstream into the develop-1 branch only to get 1714 merge conflicts

Hehe. Don't worry, we're not using that repository anymore. It was an experiment from a couple years ago, and Manifest V3 has changed slightly since then.

**Comment by WorldLanguages** [comment]
At first glance, Firefox 109 appears to be fine.
It's more modern than Chrome 95. It does not support import declarations in background scripts through with the "scripts" property, but we can continue to maintain a background.html page that includes all JS modules as `<script type="module">` tags.

**Comment by WorldLanguages** [comment]
By the way, I was wrong. The `declarativeNetRequestWithHostAccess` permission only exists since Chrome 96 (not 95).
Source: https://developer.chrome.com/docs/extensions/whats-new#chrome_96_declarativenetrequestwithhostaccess_permission

**Comment by Waakul** [comment]
> > i tried to merge the upstream into the develop-1 branch only to get 1714 merge conflicts
> 
> Hehe. Don't worry, we're not using that repository anymore. It was an experiment from a couple years ago, and Manifest V3 has changed slightly since then.

The which?

**Comment by DNin01** [comment]
> > > i tried to merge the upstream into the develop-1 branch only to get 1714 merge conflicts
> 
> > Hehe. Don't worry, we're not using that repository anymore. It was an experiment from a couple years ago, and Manifest V3 has changed slightly since then.
> 
> The which?

The ScratchAddonsMV3 repository?

**Comment by Waakul** [comment]
> > > > i tried to merge the upstream into the develop-1 branch only to get 1714 merge conflicts
> > 
> > 
> > > Hehe. Don't worry, we're not using that repository anymore. It was an experiment from a couple years ago, and Manifest V3 has changed slightly since then.
> > 
> > 
> > The which?
> 
> The ScratchAddonsMV3 repository?

The develop-1 branch on that repo is what i cloned

**Comment by WorldLanguages** [comment]
By the way, Chrome 120 reduced the minimum alarm (see `chrome.alarms`) granularity to 30 seconds, instead of 1 minute.

**Comment by WorldLanguages** [comment]
Useful links:

- [Extension Update Testing Tool](https://github.com/GoogleChromeLabs/extension-update-testing-tool) is a tool I should use to emulate a real MV2→MV3 upgrade, instead of just reloading a local extension.
- Old Chromium builds can be downloaded at https://chromium.cypress.io/ (it's broken today, unsure for how long)

**Comment by Samq64** [comment]
> - Old Chromium builds can be downloaded at https://chromium.cypress.io/ (it's broken today, unsure for how long)

The repo was archived in and the readme links to https://vikyd.github.io/download-chromium-history-version as an alternative.

**Comment by WorldLanguages** [comment]
I think v1.38.0 will be the MV3 release

**Comment by WorldLanguages** [comment]
I think I will be quite busy messing with scope:core stuff this month, so I'll be thankful if other contributors can work on getting 2 approvals for scope:addon PRs that are worth merging. It's fine to ping me though

**Comment by WorldLanguages** [comment]
> Should we start an `mv3` branch for breaking changes? MV3 pull requests could merge into that branch

Okay, I created the branch. The extension can be loaded into Chrome 121+ and Firefox 121+
If loading into Firefox, remember that the browser will not grant host permissions by default, so you need to click the "enable" button on `webpages/settings/permissions.html`.

**Comment by WorldLanguages** [comment]
Feel free to test the `mv3` branch. Most things seem to work. @DNin01 @Samq64 @mxmou

In Chromium, the background context (service worker) can be "put to sleep" by going to `chrome://serviceworker-internals`, searching for the extension ID and clicking "Stop". After interacting with the extension again (for example, opening the popup or reloading a Scratch tab) the service worker should wake up automatically.

I would assume Scratch Messaging and Scratch Notifier are broken (or work badly) unless proven otherwise.

Also note that we should test the extension in Chrome 96 and Firefox 109. In order to test in those browsers, the manifest.json file needs to be tweaked. When using Chromium, the "page" property in the "background" object should not exist. When using Firefox, the "service_worker" property of the same object should be missing instead.

**Comment by DNin01** [comment]
👏

We might also want to add some rules/protections to the new `mv3` branch.

**Comment by Waakul** [comment]
There are two problems, the indication when not signed in the setting of the badge addon just triggers randomly. The stylesheets blink sometimes.

**Comment by WorldLanguages** [comment]
@Waakul Provide enough details or a step-by-step reproduction for both issues please.

**Comment by WorldLanguages** [comment]
I created draft PR #7387 and protected the branch. Most additional discussion about the concrete code changes should belong there.

**Comment by Waakul** [comment]
> @Waakul Provide enough details or a step-by-step reproduction for both issues please.

It just happens so randomly.

**Comment by WorldLanguages** [comment]
The master branch is now a Manifest V3 extension.

**Comment by WorldLanguages** [comment]
Before releasing to 10% of Chrome users:

- [ ] Ensure gen-manifest.mjs action works properly and as expected
- [ ] Test using upgrade tool (see comment above)
- [ ] Do some general manual testing in minimum Chrome & Firefox versions
- [ ] Do some general manual testing in up-to-date Chrome & Firefox versions

**Comment by WorldLanguages** [comment]
Sent v1.38.0 for review in Chrome Web Store. Did not submit to any other stores yet.

Also pending: add v1.38.0 to scratchaddons.com/changelog

**Comment by WorldLanguages** [comment]
> There are two problems, the indicate when not signed in setting of the badge addon just triggers randomly. The stylesheets blink sometimes.

@Waakul Do you still experience any of the two issues? I believe the latter was fixed.

**Comment by Waakul** [comment]
> > There are two problems, the indicate when not signed in setting of the badge addon just triggers randomly. The stylesheets blink sometimes.
> 
> @Waakul Do you still experience any of the two issues? I believe the latter was fixed.

I'll start to use mv3 until it happens again.

**Comment by WorldLanguages** [comment]
Okay, v1.38.0 is being rolled out to a small portion of Chrome users. I will send any relevant feedback form submissions here.

**Comment by WorldLanguages** [comment]
No relevant feedback / CWS reviews yet. Increased "percentage of users to deploy this version to" to 35%

**Comment by Waakul** [comment]
> > There are two problems, the indicate when not signed in setting of the badge addon just triggers randomly. The stylesheets blink sometimes.
> 
> @Waakul Do you still experience any of the two issues? I believe the latter was fixed.

I feel it's fixed.

**Comment by WorldLanguages** [comment]
Feedback form submission:

> changes like the opacity slider and the number inputs in color picker are not working

Probably unrelated to Manifest V3.

**Comment by WorldLanguages** [comment]
At least 10,000 users are running the Manifest V3 version as of yesterday

Increased coverage to 60%
Will update to Firefox and Edge stores in a few days at most

**Comment by WorldLanguages** [comment]
Some more feedback messages

> Ever since I saw the Update UI lately my custom colors on the home page and studio would go to the OG Scratch color then in my color in a couple 1-3 sec.

> i am temporarily uninstalling scratch addons because there's a glitch that p*sses me the #$@* off
there will be times when the site reverts back to the white-purple color scheme rather than the black-orange scheme i made for it. pls fix this, i'll be using stylify to sort this issue until then

> Hey, scratch addon team, you are a part of my daily life as I use Scratch daily. I have noticed that your dark-mode addon has became a little slow after the update. It sometimes takes 1-7 seconds to load which I find a little irritating. Can you fix it or tell me if it's a problem in my browser or something?

**Comment by DNin01** [comment]
Yeah, I kind of expected that…

I would pause the rollout until we fix this.

**Comment by WorldLanguages** [comment]
I will not pause the rollout

**Comment by WorldLanguages** [comment]
We received ~5 feedback messages out of 50,000 users. You're welcome to add a notice to the feedback form where we clarify that we're aware of this issue.

**Comment by BroJac5246** [comment]
> Yeah, I kind of expected that…
> 
> I would pause the rollout until we fix this.

We can make those two issues super high-priority but we should also get MV3 out as soon as possible because MV2 will officially/supposedly be disabled in Chrome 127 (which Chrome Dev is currently on) — the deadline to avoid losing the "featured" badge is June as well.

**Comment by WorldLanguages** [comment]
Okay, one more.

> For the manifest V3, sometimes, a bug appears where my scratch page goes normal for a few seconds and then it inputs the addons in

Surprisingly, no one complained about the Scratch Notifier notification ping, nor about unprocessed HTML in notifications.

**Comment by WorldLanguages** [comment]
I'm uploading the Firefox build of v1.38.0 to the Firefox store.

About half of Chrome Web Store users are on the Manifest V3 build and it keeps increasing.
Haven't uploaded to the Edge store yet.

**Comment by WorldLanguages** [comment]
Firefox feedback:

> I'm using Firefox for Android. The new "experimental update" completely stops the extension from working

**Comment by WorldLanguages** [comment]
Okay, I give up. I have been trying to load an unpacked extension into Firefox Nightly for Android using `web-ext` for the last hour, and I cannot get it to work. So I'm only able to inspect the released version of the extension.
Here is the guide to load any extension into Android through USB and adb: https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/
