### ISSUE TITLE
(released) Tracking modern-blockly scratch-blocks rewrite

### ISSUE THREAD

**Issue by GrahamSH-LLK** [ScratchAddons/ScratchAddons#7768]
A few Google engineers are rewriting scratch-blocks to use modern Blockly. This will likely break a significant number of editor addons, as -blocks is a very old, and quite modified, fork. Below are instructions for building this rewrite locally for testing addons/extension. 

### Modern blockly scratch-blocks setup
```sh
git clone https://github.com/scratchfoundation/scratch-editor.git --branch spork --depth=1 # Git history is large
cd scratch-editor/
npm ci
npm run build
```
Once setup run `npm run start` in `scratch-editor/packages/scratch-gui` to start it on `localhost:8601`.

## Compatibility checklist

> [!NOTE]  
> This list is outdated because new bugs have been discovered after the updated editor went live on https://scratch.mit.edu.

### Enabled by default

* [x] `editor-devtools`
* [x] `find-bar`
* [x] `middle-click-popup`
* [x] `jump-to-def`
* [x] `place-backpack-code-at-cursor`
* [x] `editor-cleanup-plus`

### Recommended

* [x] `editor-number-arrow-keys`
* [x] `hide-flyout`
* [x] `fix-editor-comments`
* [x] `editor-searchable-dropdowns`
* [x] `block-switching`
* [x] `data-category-tweaks-v2`
* [x] `fix-pasted-scripts` (Does nothing, editor doesn't stick pasted scripts to mouse)
* [x] `reorder-custom-inputs`
* [x] `color-picker`
* [x] `folders`

### Featured

* [x] `zebra-striping`
* [x] `load-extensions`
* [x] `custom-zoom`
* [x] `debugger`
* [x] `block-duplicate`
* [x] `editor-comment-previews`
* [x] `block-cherry-picking` (Included in vanilla)
* [x] `hide-new-variables`
* [x] `name-backpack-items`
* [x] `rename-broadcasts`
* [x] `editor-stepping`
* [x] `blocks2image`
* [x] `script-snap`
* [x] `swap-local-global`
* [x] `variable-manager`

### Others

* [x] `number-pad`
* [x] `transparent-orphans`
* [x] `copy-reporter`
* [x] `ctrl-click-run-scripts`
* [x] `no-script-bumping`
* [x] `editor-sounds`
* [x] `editor-extra-keys`
* [x] `editor-random-direction-block`
* [x] `hide-backpack`

### Themes

* [x] `block-palette-icons`
* [x] `cat-blocks`
* [x] `editor-colored-context-menus`
* [x] `editor-compact`
* [x] `editor-theme3`
* [x] `custom-block-shape`
* [x] `custom-block-text`
* [x] `editor-stage-left`
* [x] `editor-dark-mode`
* [x] `columns`
* [x] `workspace-dots`
* [x] `editor-square-inputs`

**Comment by pufferfish101007** [comment]
As jeffalo kindly pointed out, https://gonfunko.github.io/scratch-gui/ also exists

**Comment by WorldLanguages** [comment]
This comment is interesting:

> Chris said that we didn't need to maintain [CSS attributes used by ScratchAddons*. And in general for ScratchAddons things, we shouldn't actively remove them, but we don't need to put extra effort into maintaining them.

Source is: https://github.com/gonfunko/scratch-blocks/ issues/36#issuecomment-2087609150

**Comment by mxmou** [comment]
> This comment is interesting (and makes complete sense):
> 
> > Chris said that we didn't need to maintain [CSS attributes used by ScratchAddons]. And in general for ScratchAddons things, we shouldn't actively remove them, but we don't need to put extra effort into maintaining them.

Fortunately, we don't use either attribute mentioned in that issue anymore - they were only used by theme3 before it was rewritten using Blockly. We use the related `getCategory()` method and `category_` property in a few places to check which category a block belongs to in JS, but that can also be done by splitting the opcode.

**Comment by Samq64** [comment]
> @TheColaber There's very little point in working on this. Blockly is killing setColour (https://github.com/google/blockly/issues/8280) and recommending using CSS instead.

_Originally posted by @GrahamSH-LLK in https://github.com/ScratchAddons/ScratchAddons/issues/7572#issuecomment-2409039987_

**Comment by Joeclinton1** [comment]
How long until everything breaks?

**Comment by WorldLanguages** [comment]
> How long until everything breaks?

I don't think there's any official timelines yet.

**Comment by Samq64** [comment]
Work seems to be under the codename "spork" now:
- https://github.com/scratchfoundation/scratch-gui/tree/spork
- https://github.com/scratchfoundation/scratch-vm/tree/spork
- https://github.com/scratchfoundation/scratch-blocks/tree/spork

**Comment by Samq64** [comment]
Here's my compatibility checklist with #7892 applied. Feel free to edit.

## Recommended

* [ ] `editor-number-arrow-keys` (value is not saved)
* [ ] `hide-flyout` (`recordCachedAreas` is not a function)
* [ ] `fix-editor-comments` (`ScratchBubble.prototype` is undefined)
* [ ] `editor-searchable-dropdowns`
* [ ] `block-switching` (context menu API broken)
* [ ] `data-category-tweaks-v2` (`refreshToolboxSelection_` is not a function)
* [ ] `editor-devtools` (Clean up Blocks + works)
* [ ] `fix-pasted-scripts` (Does nothing, editor doesn't stick pasted scripts to mouse)
* [ ] `find-bar`
* [ ] `middle-click-popup`
* [ ] `jump-to-def`
* [ ] `place-backpack-code-at-cursor` (untested)
* [ ] `reorder-custom-inputs` (Uses `window.Blockly`)

## Featured

* [ ] `zebra-striping`
* [x] `load-extensions`
* [ ] `custom-zoom`
* [ ] `debugger` (Threads and performance tabs seem to work)
* [ ] `block-duplicate`
* [ ] `editor-comment-previews`
* [x] `block-cherry-picking` (Included in vanilla)
* [ ] `hide-new-variables`
* [ ] `name-backpack-items` (untested)
* [ ] `rename-broadcasts`
* [ ] `editor-stepping`
* [ ] `blocks2image` (context menu API broken)
* [ ] `script-snap` (`snapToGrid_` is undefined)
* [ ] `swap-local-global`
* [ ] `variable-manager`

## Others

* [ ] `number-pad`
* [ ] `transparent-orphans` (Hat stacks still considered orphans)
* [ ] `copy-reporter` (Icon missing)
* [ ] `ctrl-click-run-scripts`
* [ ] `no-script-bumping`
* [ ] `editor-sounds` (`loadSounds_` is not afunction)
* [x] `editor-extra-keys`
* [x] `editor-random-direction-block`
* [ ] `hide-backpack`

## Themes

* [ ] `block-palette-icons`
* [ ] `cat-blocks`
* [ ] `editor-colored-context-menus`
* [ ] `editor-compact` (category selector unstyled)
* [ ] `editor-theme3`
* [ ] `custom-block-shape` (Bold text setting and dynamic setting changes don't work)
* [x] `editor-stage-left`
* [ ] `editor-dark-mode`
* [ ] `columns`
* [ ] `workspace-dots`
* [ ] `editor-square-inputs`

**Comment by mxmou** [comment]
I'm currently working on updating themes, specifically editor dark mode.

**Comment by Samq64** [comment]
It looks like scratch-blocks will be ported to TypeScript at the same time: https://github.com/gonfunko/scratch-blocks/pull/224

**Comment by GarboMuffin** [comment]
Since modern versions of google/Blockly are written in TypeScript, it has very good type information that we can use to statically find errors. This does not require writing any TypeScript or adding a build step. If we're adding types for Blockly we may as well do the rest of Scratch.

As a proof I concept, I have created https://github.com/GarboMuffin/ScratchAddons/commits/types-2024/ which adds types for:

 - `addon.tab.traps.vm`
 - `addon.tab.traps.getBlockly()`
 - `addon.tab.traps.getWorkspace()`
 - `addon.tab.redux.state`
 - `addon.tab.redux.dispatch()`

Using these from a userscript just requires adding `/** @param {UserscriptUtilities} param0 */` to the function definition.

Some examples of errors this detects:

Variables.createVariable is no longer public:

![image](https://github.com/user-attachments/assets/8a8b644e-c74e-470b-8ad6-cb3331da01ca)

getConnections_() is supposed to always take an argument (this has probably always been the case):

![image](https://github.com/user-attachments/assets/0a8104a5-ed23-493a-973d-1d7d3816ca26)

ScratchMsgs no longer exists:

![image](https://github.com/user-attachments/assets/469c1517-7133-41f4-8a8a-835722de371f)

The types want this to be "getGrid()" instead:

![image](https://github.com/user-attachments/assets/3b07f94d-1a10-4dc7-8193-0e5ac6696974)

Reasonably important caveats:

 - I am adding npm dependencies. This could be avoided by using the global TypeScript installation (like how we're doing Prettier) and manually copying and pasting very large .d.ts files into the repository.
 - There are a lot of type errors completely unrelated to the new Blockly. At least a few of these type errors are probably real bugs.
 - I am using types built from google/blockly, not scratchfoundation/scratch-blocks#spork
 - The types for scratch-gui, scratch-vm, etc. are written by hand and contain some errors. Also, redux types are missing scratch-www.
 - You will get type errors when using private class variables, but they are still listed in the types. It wouldn't be too hard to make a script/modified compiler that removes the privacy from fields. However many things that were previously private-but-actually-public are now local variables in a module so I don't think we can easily access them anymore regardless.

**Comment by DNin01** [comment]
Are there any improvements and fixes to code comments in this update?

**Comment by Samq64** [comment]
The only thing I've noticed is fixed is the clipping.

**Comment by mxmou** [comment]
<del>Many comment bugs are related to how they're saved and loaded, which is handled by the VM.</del>

Edit: I don't know why I thought that - it doesn't make sense. The VM treats block comments almost exactly the same way as workspace comments, so any bugs caused by it would affect both.

**Comment by Joeclinton1** [comment]
An idea for the lowest effort approach to fixing this. We identify the most popular addons, which absolutely cannot be allowed to break. We make sure those will work. Then we just wait until the update causes the others to break. Then we do a team effort to fix them.

**Comment by WorldLanguages** [comment]
[Here](https://github.com/scratchfoundation/scratch-editor/pull/../pull/17#issue-2504889598) I found something interesting:

> I haven't included any state management solutions intentionally - while Redux is regularly associated with React, I've found it to be unnecessary and inconvenient most of the time, especially for sites with not a lot of dynamic global state (which should be most, including this one). Usually state is page-based and can be hosted in page components. For instances of global state we can use useContext & useReducer where necessary.

I haven't read it fully so I don't really know if they're talking about Redux being unnecessary for the website or for the editor. Actually, we don't even know what NGP ("next generation project") actually refers to.
Nevertheless, tt is a fact that Scratch probably uses Redux more than it should, both in the editor and www, and that usually made modding easier.

**Comment by Samq64** [comment]
`scratch-blocks` now has a [draft PR](https://github.com/scratchfoundation/scratch-blocks/pull/3338) to merge everything into develop. I don't see one yet on the other repos though.

**Comment by Wowfunhappy** [comment]
> I don't see one yet on the other repos though.

There is now a PR for their new "Scratch Editor" monorepo: https://github.com/scratchfoundation/scratch-editor/pull/214/commits

**Comment by Joeclinton1** [comment]
Could we not just ask them straight up when they plan to deploy to production?

**Comment by mxmou** [comment]
I've marked variable-manager as done - it only interacts with Blockly when renaming variables and that seems to work correctly.

**Comment by Samq64** [comment]
A status update from an ST member: https://github.com/scratchfoundation/scratch-editor/pull/214#issuecomment-2770736208

**Comment by Joeclinton1** [comment]
@mxmou thank you for going through so many addons to check them, that must have taken a while. So are the remaining addons going to break with the changes?

- [x] zebra-striping
- [ ] name-backpack-items
- [x] cat-blocks
- [x] custom-block-shape

**Comment by Samq64** [comment]
They don't work but also don't break anything else when enabled.

**Comment by WorldLanguages** [comment]
Anyone know when the changes are coming?

**Comment by mxmou** [comment]
> Anyone know when the changes are coming?

I think the most recent update from the ST about this is the one linked by @Samq64 above, which says the PR will be merged "sometime this summer".

**Comment by Samq64** [comment]
The `spork` branch has been deployed at https://scratchfoundation.github.io/scratch-editor/spork/scratch-gui/ ~~but the extension isn't configured to run there yet.~~

**Comment by FlamedDogo99** [comment]
The addon `editor-theme3` is not fully compatible with new Blockly yet.
When you enable the addon late, edit a block, and then interact with the related procedure_prototype, the block becomes deformed.

https://github.com/user-attachments/assets/f8c71b74-1e41-4381-8f4a-ba73e555cd0b

**Comment by Samq64** [comment]
> They don't work but also don't break anything else when enabled.

Actually `zebra-striping` crashes the editor when clicking make a block.

Edit: I was replying to https://github.com/ScratchAddons/ScratchAddons/issues/7768#issuecomment-3103936677, not the last comment.

**Comment by mxmou** [comment]
> > They don't work but also don't break anything else when enabled.
> 
> Actually `zebra-striping` crashes the editor when clicking make a block.

Can repro. If the addon isn't updated in time, we should at least fix the crash.

**Comment by Samq64** [comment]
A couple of workarounds will not be necessary thanks to upstream improvements:
- Blockly's context menu API now supports separators
- Subsequent blocks are once again duplicated (I should have known it was a bug)

**Comment by mxmou** [comment]
Update about the planned release date from a Scratch developer: according to [this talk](https://www.youtube.com/watch?v=SO0ktLgIlSs) (timestamp: 4:19), they're "hoping to finish unforking this year".

**Comment by Samq64** [comment]
Thank you @mxmou for all your hard work over the past several months preparing for this!

**Comment by Joeclinton1** [comment]
> Thank you [@mxmou](https://github.com/mxmou) for all your hard work over the past several months preparing for this!

@mxmou Yes, thank you! It seems you and @Samq64 have single handedly prevented a massive number of bugs that could've tarnished the addons reputation.

**Comment by mxmou** [comment]
@Samq64 Thanks for reviewing and testing the PRs! You found a lot of bugs that I missed.

**Comment by Samq64** [comment]
I'm reposting the Blockly CSS migration document here in case someone finds it useful: https://docs.google.com/document/d/1JLSuu0yqK9Yu9tx0zugBzlcA7qFcpX9bfHh15LDt29c

**Comment by WorldLanguages** [comment]
Thanks everyone!

After Scratch migrates to new blockly, maybe we could briefly add a symbolic, zero lines of code addon, named along the lines of `Compatibility with the recent Scratch update`, to the top of the settings page. Using `latestUpdate` for dozens of addons would be nuts, so instead we could use the Credits field of the new "addon" appropriately.

**Comment by Samq64** [comment]
I think just mentioning it in the update notification and changelog is enough.

**Comment by Waakul** [comment]
The vm no longer contains store? What is the new way to save the project through userscripts.

**Comment by mxmou** [comment]
> The vm no longer contains store? What is the new way to save the project through userscripts.

If you mean storage, the new way to access it is `addon.tab.redux.state.scratchGui.config.storage`. This is unrelated to the Blockly update.

**Comment by Samq64** [comment]
`folders` wasn't on the list but it needs to be updated as well.

**Comment by mxmou** [comment]
> `folders` wasn't on the list but it needs to be updated as well.

Which part of it doesn't work?

**Comment by Samq64** [comment]
I can't repro anymore, there are a few console errors but the addon seems to be working fine. Yesterday I couldn't create a folder.

**Comment by Samq64** [comment]
@GrahamSH-LLK found this which might affect Scratch un-forking Blockly:
https://opensource.googleblog.com/2025/10/blockly-graduates-from-google.html

**Comment by Samq64** [comment]
After enabling all addons I see 3 addon console errors:
- `editor-sounds/userscript.js:22`: `audioMgr.preload()` is not a function
- `custom-block-shape/modern-blockly.js:8` and `cat-blocks/userscript.js:327` (Scratch renamed the renderer class)

Because there is a dedicated cat blocks renderer now will there be problems with simply renaming the `scratch` references to `scratch_classic` for those with the membership?

**Comment by Samq64** [comment]
The `scratch-blocks` `spork` branch has been merged into `develop` with `scratch-editor` likely following very shortly.

**Comment by pufferfish101007** [comment]
`scratch-editor` has also had the `spork` branch merged into `develop`

**Comment by mxmou** [comment]
Looks like spork will be released soon. See the pull "release/2026-04-08" branch in scratch-www, which updates the scratch-gui version.

**Comment by mxmou** [comment]
Now that the backpack crash is fixed, name-backpack-items works correctly on the spork branch (which isn't surprising since the backpack API hasn't changed).

**Comment by Joeclinton1** [comment]
The spork branch has been merged in. I vote we make a new issue, like this one but tracking the known bugs, now that it's in production.

**Comment by Joeclinton1** [comment]
I'm going to fix my own addons first.

**Comment by Samq64** [comment]
When should the old Blockly code be cleaned up? As addons are fixed/changed, 1.46, or the backlog?

**Comment by Joeclinton1** [comment]
https://github.com/scratchfoundation/scratch-editor/issues/533 the equivalent discussion but for scratch themselves

**Comment by DNin01** [comment]
The font of the blocks changed on the Scratch website. That must mean that Blockly was updated. Was it?

(The font is supposed to be unchanged, BTW. I kind of enjoy the new one though.)

**Comment by Joeclinton1** [comment]
> The font of the blocks changed on the Scratch website. That must mean that Blockly was updated. Was it?

Yeh that's what I'm saying. It has been deployed to production as of yesterday.

**Comment by WorldLanguages** [comment]
Please ping me when v1.45.1 is ready for release. Thanks

**Comment by WorldLanguages** [comment]
We could also release 2 patch releases one after the other if we want to ship the existing bug fixes faster.

**Comment by mxmou** [comment]
> We could also release 2 patch releases one after the other if we want to ship the existing bug fixes faster.

If we do that, #8987 should probably be merged before releasing the first patch.

**Comment by DNin01** [comment]
Wouldn't it be funny if Scratch rolled back the Blockly update after we [remove our old Blockly code](https://github.com/ScratchAddons/ScratchAddons/pull/9066)? I don't see why they would, but just saying, you know, would it hurt to be prepared to hotfix back in the old Blockly code in that rare case? lol

**Comment by Samq64** [comment]
That's unlikely because it has been a couple of months and the `project.json` not fully backwards compatible.
